package day3;

import java.io.FileWriter;
import java.io.IOException;

public class ExceptionLesson {

	public static void main(String[] args)throws InterruptedException {
	FileWriter fw=null;
		try {
			fw=new FileWriter("data.txt");
			fw.write("Hello");
		}catch(Exception e){
			System.out.println("何らかの例外が発生しました");
		}finally{
			if(fw!=null) {
				try {
					fw.close();
				}catch(IOException e) {
					;
				}
			}
		}
		sleep();
		String s=null;
		try {
			System.out.println(s.length());
		} catch (Exception e) {
			// TODO 自動生成された catch ブロック
			e.printStackTrace();
		}
	}
	static void sleep() throws InterruptedException{
		Thread.sleep(3000);
	}
}
